/**
 * Idempotent seed script.
 *
 * Projects the in-code datasets into Postgres:
 *   src/units/conversionData.ts -> unit_conversions
 *   src/data/shelfLife.ts       -> shelf_life_reference
 *   (plus the single preferences row)
 *
 * Safe to re-run. Every seeded row carries a stable `seed_key`, and the upsert
 * targets that column, so re-running updates the rows this script owns and
 * leaves anything you added by hand (seed_key null) completely alone.
 *
 * Usage:
 *   npm run seed              apply to the database in .env.local
 *   npm run seed:dry          build and validate everything, touch nothing
 *   npm run seed:sql          write supabase/seed.sql instead of connecting
 */

import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createClient, type SupabaseClient } from '@supabase/supabase-js';

import { SHELF_LIFE_REFERENCE } from '../src/data/shelfLife.js';
import { buildConversionRules } from '../src/units/conversionRules.js';
import type { ConversionRule } from '../src/units/types.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = resolve(HERE, '..');

/** Supabase rejects very large single inserts; 500 rows is comfortably under. */
const CHUNK_SIZE = 500;

// ---------------------------------------------------------------------------
// Row shaping
// ---------------------------------------------------------------------------

interface UnitConversionRow {
  item_name_pattern: string | null;
  category: string | null;
  from_unit: string;
  to_canonical_unit: string;
  multiplier: number;
  confidence: string;
  notes: string | null;
  seed_key: string;
}

interface ShelfLifeRow {
  category: string;
  item_name_pattern: string | null;
  days_refrigerated: number | null;
  days_pantry: number | null;
  days_frozen: number | null;
  confidence: string;
  notes: string | null;
  seed_key: string;
}

function toUnitConversionRow(rule: ConversionRule): UnitConversionRow {
  return {
    item_name_pattern: rule.itemNamePattern,
    category: rule.category,
    from_unit: rule.fromUnit,
    to_canonical_unit: rule.toCanonicalUnit,
    // 8 significant figures. Far more precision than any of these estimates
    // carry, and it keeps the table readable instead of full of 0.3333333333333333.
    multiplier: Number(rule.multiplier.toPrecision(8)),
    confidence: rule.confidence,
    notes: rule.notes ?? null,
    seed_key: rule.seedKey,
  };
}

function toShelfLifeRows(): ShelfLifeRow[] {
  return SHELF_LIFE_REFERENCE.map((entry) => ({
    category: entry.category,
    item_name_pattern: entry.itemNamePattern,
    days_refrigerated: entry.daysRefrigerated,
    days_pantry: entry.daysPantry,
    days_frozen: entry.daysFrozen,
    confidence: entry.confidence,
    notes: entry.notes ?? null,
    seed_key: entry.seedKey,
  }));
}

// ---------------------------------------------------------------------------
// SQL emitter (for `supabase db reset` / running by hand in the SQL editor)
// ---------------------------------------------------------------------------

function sqlLiteral(value: string | number | null): string {
  if (value === null) return 'null';
  if (typeof value === 'number') {
    if (!Number.isFinite(value)) throw new Error(`Refusing to emit non-finite number: ${value}`);
    return String(value);
  }
  return `'${value.replace(/'/g, "''")}'`;
}

function emitInsert(table: string, rows: Array<Record<string, string | number | null>>): string {
  if (rows.length === 0) return '';
  const columns = Object.keys(rows[0] as Record<string, unknown>);
  const updates = columns
    .filter((column) => column !== 'seed_key')
    .map((column) => `${column} = excluded.${column}`)
    .join(',\n    ');

  const values = rows
    .map((row) => `  (${columns.map((column) => sqlLiteral(row[column] ?? null)).join(', ')})`)
    .join(',\n');

  return (
    `insert into ${table} (${columns.join(', ')})\nvalues\n${values}\n` +
    `on conflict (seed_key) do update set\n    ${updates};\n`
  );
}

function buildSql(conversions: UnitConversionRow[], shelfLife: ShelfLifeRow[]): string {
  const header = [
    '-- Generated by scripts/seed.ts. Do not edit by hand -- edit the datasets in',
    '-- src/units/conversionData.ts and src/data/shelfLife.ts and regenerate.',
    '--',
    '-- Idempotent: every row is keyed by seed_key, so re-running updates the',
    '-- seeded rows and leaves hand-added rows (seed_key null) untouched.',
    '',
    'begin;',
    '',
  ].join('\n');

  const preferences =
    "insert into preferences (id) values (1) on conflict (id) do nothing;\n";

  return [
    header,
    preferences,
    '',
    emitInsert('unit_conversions', conversions as unknown as Array<Record<string, string | number | null>>),
    '',
    emitInsert('shelf_life_reference', shelfLife as unknown as Array<Record<string, string | number | null>>),
    '',
    'commit;',
    '',
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Database application
// ---------------------------------------------------------------------------

type SeedRow = UnitConversionRow | ShelfLifeRow;

async function upsertChunked(
  client: SupabaseClient,
  table: string,
  rows: SeedRow[],
): Promise<void> {
  for (let start = 0; start < rows.length; start += CHUNK_SIZE) {
    const chunk = rows.slice(start, start + CHUNK_SIZE);
    const { error } = await client
      .from(table)
      // The client is untyped here (no generated Database types yet), so the
      // row shape is checked by SeedRow above rather than by supabase-js.
      .upsert(chunk as never, { onConflict: 'seed_key' });
    if (error) {
      throw new Error(
        `Failed to upsert ${chunk.length} rows into ${table} ` +
          `(rows ${start}-${start + chunk.length - 1}): ${error.message}` +
          (error.hint ? `\n  hint: ${error.hint}` : '') +
          (error.details ? `\n  details: ${error.details}` : ''),
      );
    }
    process.stdout.write(`  ${table}: ${Math.min(start + CHUNK_SIZE, rows.length)}/${rows.length}\n`);
  }
}

function loadEnv(): void {
  for (const file of ['.env.local', '.env']) {
    try {
      process.loadEnvFile(resolve(PROJECT_ROOT, file));
      return;
    } catch {
      // Missing file is fine; the next candidate or the real environment wins.
    }
  }
}

function requireEnv(name: string): string {
  const value = process.env[name];
  if (!value || value.trim() === '') {
    throw new Error(
      `${name} is not set. Copy .env.example to .env.local and fill it in ` +
        '(Supabase dashboard -> Project Settings -> API).',
    );
  }
  return value.trim();
}

async function applyToDatabase(
  conversions: UnitConversionRow[],
  shelfLife: ShelfLifeRow[],
): Promise<void> {
  const url = requireEnv('SUPABASE_URL');
  const key = requireEnv('SUPABASE_SERVICE_ROLE_KEY');

  const client = createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  console.log(`Seeding ${new URL(url).host} ...`);

  // The single preferences row. `ignoreDuplicates` matters: re-seeding must not
  // reset preferences the user has since edited.
  const { error: preferencesError } = await client
    .from('preferences')
    .upsert({ id: 1 }, { onConflict: 'id', ignoreDuplicates: true });
  if (preferencesError) {
    throw new Error(`Failed to ensure the preferences row: ${preferencesError.message}`);
  }

  await upsertChunked(client, 'unit_conversions', conversions);
  await upsertChunked(client, 'shelf_life_reference', shelfLife);
}

// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const dryRun = args.includes('--dry-run');
  const emitSqlIndex = args.indexOf('--emit-sql');
  const emitSqlPath = emitSqlIndex >= 0 ? args[emitSqlIndex + 1] : undefined;

  if (emitSqlIndex >= 0 && !emitSqlPath) {
    throw new Error('--emit-sql needs an output path, e.g. --emit-sql supabase/seed.sql');
  }

  // buildConversionRules() throws on a duplicate (scope, unit) pair, which is
  // exactly the constraint the migration's unique indexes enforce. Failing here
  // is much easier to debug than failing mid-upsert.
  const conversions = buildConversionRules().map(toUnitConversionRow);
  const shelfLife = toShelfLifeRows();

  const seedKeys = new Set([...conversions, ...shelfLife].map((row) => row.seed_key));
  if (seedKeys.size !== conversions.length + shelfLife.length) {
    throw new Error('Duplicate seed_key across datasets; the upsert would silently drop rows.');
  }

  console.log(`Built ${conversions.length} unit conversions and ${shelfLife.length} shelf-life rows.`);

  if (emitSqlPath) {
    const outputPath = resolve(PROJECT_ROOT, emitSqlPath);
    writeFileSync(outputPath, buildSql(conversions, shelfLife), 'utf8');
    console.log(`Wrote ${outputPath}`);
    return;
  }

  if (dryRun) {
    console.log('Dry run: nothing was written. Re-run without --dry-run to apply.');
    return;
  }

  loadEnv();
  await applyToDatabase(conversions, shelfLife);
  console.log('Done. Re-running this script is safe and will not duplicate anything.');
}

main().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : String(error);
  console.error(`\nSeed failed: ${message}`);
  process.exitCode = 1;
});
